# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

draft: false
acme:
  email_account: ${CLOUDFLARE_AUTH_USERNAME}
  staging: false
  crontab_renew: 12 01,13 * * *
  certs_permissions:
    files_mode: 0644
    dirs_mode: 0755
    # user: nobody
    # group: nogroup

profiles:
  - name: cloudflare
    provider: cloudflare
    provider_options:
      auth_username: ${CLOUDFLARE_AUTH_USERNAME}
      auth_token: ${CLOUDFLARE_AUTH_TOKEN}
      zone_id: ${CLOUDFLARE_ZONE_ID}

certificates:
  - name: wg.ghuntley.net
    profile: cloudflare
    force_renew: false
    domains:
      - "*.wg.ghuntley.net"
    autorestart:
      - containers:
          - ingress

  - name: ghuntley.net
    profile: cloudflare
    force_renew: false
    domains:
      - "*.ghuntley.net"
    autorestart:
      - containers:
          - ingress

  - name: ghuntley.dev
    profile: cloudflare
    force_renew: false
    domains:
      - "*.ghuntley.dev"
    autorestart:
      - containers:
          - ingress
